### ISSUE TITLE
Create conda packages

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#107]
https://github.com/conda-forge/staged-recipes/pull/3116

**Comment by lrntct** [comment]
I've created a conda package for swmm:
https://github.com/conda-forge/staged-recipes/pull/11903

Now that it's all in the green, I'd like to add pyswmm to the PR. I wonder what would be the best approach for using the dll from the swmm conda package and not the one from the pyswmm package.
I would propose to change the dll discovery code as follows:
- First, use the dll from the user
- If not, search for the DLL in sys.prefix    <== this is new
- If not, use the dll from the pypi package

@bemcdonnell any thought?

**Comment by lrntct** [comment]
The package at https://anaconda.org/conda-forge/pyswmm/files should now work. You are welcome to try.
Because of #240 , the changes proposed in #241 are integrated via a forked package. Hopefully, in the future either #241 is merged or #240 is solved, so the conda package can rely directly on the pyswmm package.

**Comment by mrustl** [comment]
Would be happy to see v1.0.1 on conda as I have problems installing the latest version using `pip` ....

**Comment by michaeltryby** [comment]
What problem are you having? Are you running pyswmm on Linux?
