### ISSUE TITLE
Time series at node

### ISSUE THREAD

**Issue by jsadler2** [OpenWaterAnalytics/pyswmm#149]
Hi @bemcdonnell , does pyswmm currently have the ability to get a time series of results for a given node or conduit? For example, if I wanted the time series at node "j1" currently the only way I know how to do that is to append `j1.depth` and `sim.current_time` at every time step to a list. I've noticed that the generated '.rpt' file has the time series, but I don't see a way to read that through pyswmm currently.

**Comment by bemcdonnell** [comment]
@jsadler2, It sounds like you are interested in doing post-processing type analyses with a full timeseries.  At the moment, PySWMM does not build any timeseries array for you. However, we are going to migrate the OutputAPI into pyswmm so that you will have the option to read the binary output files.  If you're interested in using it in its low-level api form, go here:

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/develop/tools/swmm-output 

To build this tool you'll need to have SWIG installed. It is a python extension so the library is actually C code that is compiled and wrapped with a thin python layer.  It can be very fast.  

We're going to migrate this toolbox into pyswmm pretty soon so thanks for your patience!

**Comment by Jiadalee** [comment]
I have the same question for getting the time-series output. What is the best way to accomplishing this now?
