### ISSUE TITLE
Building getter / setter for pollutant buildup of multi pollutants for subcatchments

### ISSUE THREAD

**Issue by ngg-osu** [OpenWaterAnalytics/pyswmm#169]
Hi, like to ask if it's possible to build a getter / setter in subcatchment.py for pollutant buildup, before and during a run?

From my limited understanding, the pollutants is stored in an array called "PollutArray" in toolkitapi.py. 
Is this where one can get / set?

Also, in toolkitapi.py, the line "initBuildup = 5" is commented out. Is there a reason? Thanks!

**Comment by katmratliff** [comment]
hi @ngg-osu, I have already written a getter for pollutant buildup. It currently resides in the subcatchment statistics dict, but I've done some re-working of the code to make a separate dict of subcatchment-related pollutant values. I'm planning to submit a pull request to the repository today.

**Comment by katmratliff** [comment]
I should also note that I haven't worked on making a setter yet, but that's on my to-do list for down the road.

**Comment by ngg-osu** [comment]
thanks @katmratliff , I did manage to get the subcatchment pollutant buildup values during a simulation run. It's like a nested dictionary. I'm just wondering how the returned array works in the first place.  Is it  a pointer to the first element of the PollutArray?   With prior knowledge of number of pollutants in simulation,  could one use the pointer (to memory address of 1st element) and "set" the desired value accordingly?

**Comment by katmratliff** [comment]
@ngg-osu the dictionary will be built with all of the pollutant values (not just the first one). It's a little bit trickier to handle than a regular getter/setter because the number of pollutants can vary, so the code needs to work for all potential cases. I think it should be straightforward to set the values, but I haven't had a chance to look into that myself. I'm working on testing and debugging some reworking of the pollutants API (adding a getter for concentration of pollutants in ponded water on a subcatchment). If you'd like to take a look at how I'm restructuring the pollutants API, take a look at these repositories:
https://github.com/katmratliff/pyswmm
https://github.com/katmratliff/Stormwater-Management-Model
