### ISSUE TITLE
 Automate running multiple EPA SWMM Input files ?

### ISSUE THREAD

**Issue by wujinshi** [OpenWaterAnalytics/pyswmm#222]
Hey guys, Does anybody know of a way to automate running multiple EPA SWMM Input files use pyswmm?  Cause I want to do some sensitvie analysis, so I need to creat mutiple inp files by a template inp files? How to do it ? Any suggestions would be helpful. Thank you!

**Comment by bemcdonnell** [comment]
@wujinshi, I am assuming you’re asking about running simulations in parallel. Today SWMM is not thread safe / re-entrant. Therefore if you try to open multiple files up in one instance of Python, the second file will walk on top of the first files memory space. You can work around this by using python Subprocess combined with Threading library.  This will enable you to run any number of simulations in parallel.

**Comment by MortenGrum** [comment]
I know this is old but seeing it's open: 

I just ran two test. Multiprocessing worked fine with pyswmm (using this api https://docs.python.org/3/library/multiprocessing.html) but multithreading with python's thread api did not work.

**Comment by bemcdonnell** [comment]
@MortenGrum, can you share the code for these two tests?  We have been successful running multiple models in parallel using python's `subprocess` combined with `threading` packages.

**Comment by MortenGrum** [comment]
Sure. I will need to simplify compared to the code I have now (which is mixed with other stuff). I'll try share it in the weekend.

**Comment by bemcdonnell** [comment]
@MortenGrum, that would be awesome.  I will put them in some examples for PySWMM so that it will help others out.

**Comment by FarisCS** [comment]
> Sure. I will need to simplify compared to the code I have now (which is mixed with other stuff). I'll try share it in the weekend.

Did you get around to sharing the test? I am attempting a similar task and that would be very helpful.

**Comment by MortenGrum** [comment]
Yes @FarisCS, I finally did and here it is:

Using a pipe to return data from subprocesses to the main process:

```
import os
import pyswmm
import multiprocessing as mp

def worker(swmm_filename, pipe_send_end):
    print("Starting:", swmm_filename)
    sim = pyswmm.Simulation(swmm_filename)
    sim.execute()
    pipe_send_end.send("Done with:" + swmm_filename)

def main():
    swmm_basenames = [ "Example1.inp", "Example2.inp", "Example3.inp", "Example4.inp" ]
    swmm_filenames = [ os.path.join(os.getcwd(), basename)  for basename in swmm_basenames ]

    processes = []
    pipes = []
    for swmm_filename in swmm_filenames:
        pipe_recv_end, pipe_send_end = mp.Pipe(False)
        p = mp.Process(target=worker, args=(swmm_filename, pipe_send_end))
        processes.append(p)
        pipes.append(pipe_recv_end)
        p.start()

    [ p.join() for p in processes ]
    results = [ pipe.recv() for pipe in pipes ]

    print(results)

if __name__ == '__main__':
    main()
```

If you don't need to return anything from the sub-processes it gets even simpler:

```
import os
import pyswmm
import multiprocessing as mp

def worker(swmm_filename):
    print("Starting:", swmm_filename)
    sim = pyswmm.Simulation(swmm_filename)
    sim.execute()

def main():
    swmm_basenames = [ "Example1.inp", "Example2.inp", "Example3.inp", "Example4.inp" ]
    swmm_filenames = [ os.path.join(os.getcwd(), basename)  for basename in swmm_basenames ]

    processes = []
    for swmm_filename in swmm_filenames:
        p = mp.Process(target=worker, args=(swmm_filename, ))
        processes.append(p)
        p.start()

    [ p.join() for p in processes ]

    print("All done")

if __name__ == '__main__':
    main()
```

This is tested with python version 3.8.6 and pyswmm 1.1.0 on Windows 10.

Note that there are differences between processes on different operating systems, so it may need some adjusting to run on linux or mac.

Another thing is that if this code is to be run in a subprocess itself, the parent process must be set to demon false.

If you have really many parallel simulations you'd probably want to use a pool as shown in the docs (avoid crashing due to memory issues). Note that the multiprocessing only supports pooling run from the main process. But you could manage it yourself and obtain a slightly smaller performance boost.  

See also [the multiprocessing docs here.](https://docs.python.org/3/library/multiprocessing.html)

@bemcdonnell, I hope this works as examples.

**Comment by bemcdonnell** [comment]
@MortenGrum, nice example. This is quite similar to how we do it at Xylem.  I can work with the team to persist this into some examples. Thanks!
