### ISSUE TITLE
Wrong sign on flow (compared to SWMM5 definition)

### ISSUE THREAD

**Issue by MortenGrum** [OpenWaterAnalytics/pyswmm#302]
**Issue**
In SWMM5 flow is positive if it flows in the direction that the link is defined and negative if it flows against the direction that the link is defined. In pyswmm this does not seem to be the case.

**To Reproduce It**
Run the attached *.inp file in SWMM5 and the same setup via pyswmm as follows:
```
import matplotlib.pyplot as plt
from pyswmm import Simulation, Links

with Simulation('test_flow_directions.inp') as sim:
    sim.step_advance(60)

    t = []
    flows = [[], [], []]

    for step in sim:

        t.append(sim.current_time)
        l = 0
        for link in Links(sim):
            flows[l].append(link.flow) 
            l = l+1

fig, ax = plt.subplots()
ax.plot(t, flows[0])
ax.plot(t, flows[1])
ax.plot(t, flows[2])
plt.show()
```

**Expected flow in link 2 (SWMM5 GUI)**
As expected, the flow in link 2 is negative because I defined it from its downstream end to its upstream end. 
![image](https://user-images.githubusercontent.com/3153092/135053235-721c0640-70e4-4ce3-88e9-a9de928f2c67.png)

**Observed flow in link 2 (using the pyswmm code above)**
Surprisingly, the flow in link 2 is not negative. 
![image](https://user-images.githubusercontent.com/3153092/135054672-6ab4e44d-85c5-406d-85f1-74788e41a2bf.png)

**Bug?**
Is this a bug or a difference in convention? If the latter, what is then the convention in pyswmm?

Thanks in advance!

**Versions:**
 - OS: Windows 10
 - Python Version 3.8.6
 - PySWMM Version 1.0.1

**Attached .inp file**
Here is the *.inp file (added txt ending just so I could upload to github)
[test_flow_directions.inp.txt](https://github.com/OpenWaterAnalytics/pyswmm/files/7242397/test_flow_directions.inp.txt)

**Comment by bemcdonnell** [comment]
@MortenGrum great bug report. Agree. This is a bug. 

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/8e4610611ae3d61edac53518dc65d67108b400f3/src/solver/toolkit.c#L2007 Is supposed to be multiplied by a link flow direction variable. To the best of my knowledge, this was happening in a previous version of pyswmm/owa-swmm. @jennwuu @michaeltryby, we have a link direction method exposed through the API. Did something change?

**Comment by bemcdonnell** [comment]
@MortenGrum Ok, I've done a little more research into this.  The reason we are seeing positive values is due to the solver.  When the model is loaded, based on the slope of the pipes, a link is reversed inside SWMM to keep a positive slope between the nodes.  As a result, swmm solves flows with the link reversed and when we output to the OUT/RPT files, the flows are multipled by -1 for those reversed links.  The follow variable is stored

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/8e4610611ae3d61edac53518dc65d67108b400f3/src/solver/objects.h#L677

When we scrape results from the running sim, you are seeing the number that the solver sees.  What we should be doing inside the API is multiplying the output for flow by the flow direciton value (which is either 1 or -1).  

I have a suggested work around (which isn't beautiful but might help you until we can make the next release). 

```python
import matplotlib.pyplot as plt
from pyswmm import Simulation, Links

with Simulation('test_flow_directions.inp') as sim:
    sim.step_advance(60)

    t = []
    flows = [[], [], []]

    for step in sim:

        t.append(sim.current_time)
        l = 0
        for link in Links(sim):
            flows[l].append(link.flow * sim._model._getLinkDirection(link.linkid) ) 
            l = l+1

fig, ax = plt.subplots()
ax.plot(t, flows[0])
ax.plot(t, flows[1])
ax.plot(t, flows[2])
plt.show()
```
Full disclosure, I did not try to run this code.  Please let me know if this doesn't work!


@jennwuu and @michaeltryby, to the best of my UPDATED knowledge, we never correct the output. :)

**Comment by jennwuu** [comment]
Thank you for looking into this @bemcdonnell! 

Should we create an issue for this in OWA/SWMM or should we correct the output in pyswmm?

CC: @michaeltryby

**Comment by bemcdonnell** [comment]
@jennwuu, this is a SWMM issue so let’s raise it there. It’s API

**Comment by jennwuu** [comment]
Ok, issue created and will be addressed in OWA/SWMM: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/issues/353

**Comment by MortenGrum** [comment]
Thanks @bemcdonnell and @jennwuu!!

For now that's clarification enough for me. I've now created a rule base on link's invert levels of input and output nodes.

Should this get changed in the API (and so pyswmm too) I will probably notice.

**Comment by bemcdonnell** [comment]
@MortenGrum, let me know if my code suggestion works.  That should avoid any extra coding for you!

```python
flows[l].append(link.flow * sim._model._getLinkDirection(link.linkid) ) 
```

**Comment by jennwuu** [comment]
Hi @MortenGrum, I will keep this issue open until it has been resolved. Thanks for identifying this bug. The report is super helpful.
